--- # delete bucket
- hosts: localhost
  connection: local
  remote_user: ansible
  gather_facts: no
  become: yes
  vars_files:
   - /home/ansible/key.yml
  tasks:
   - name: crate bucket 
     aws_s3:
      aws_access_key: "{{ aws_key }}"
      aws_secret_key: "{{ aws_secret }}"
      region: "{{ aws_region }}"
      bucket: mokshateja
      mode: delete
