--- # create bucket and copy object 
- hosts: localhost
  connection: local
  remote_user: ansible
  gather_facts: no
  become: yes
  vars_files:
   - /home/ansible/key.yml
  tasks:
   - name: crate bucket 
     aws_s3:
      aws_access_key: "{{ aws_key }}"
      aws_secret_key: "{{ aws_secret }}"
      region: "{{ aws_region }}"
      bucket: mokshateja
      mode: create
      permission: public-read-write
   - name: copy objects into newly crated bucket.
     aws_s3:
      aws_access_key: "{{ aws_key }}"
      aws_secret_key: "{{ aws_secret }}"
      region: "{{ aws_region }}"
      bucket: mokshateja
      mode: put
      object: /test/iam.yml
      src: iam.yml
