--- # create ami instance
- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  vars_files: 
   - /home/ansible/key.yml
  tasks:
   - name: create ami instance
     ec2_ami:
      region: "{{ aws_region }}"
      aws_access_key: "{{ aws_key }}"
      aws_secret_key: "{{ aws_secret }}"
      instance_id: i-0bf3dd2dcf3519a4c
      name: myimage
      tags:
       Name: test
       Service: database
     register: instance
