--- # create 1 gb standard stoage and assing to specific instance.
- hosts: localhost
  connection: local
  remote_user: ansible
  gather_facts: no
  become: yes
  vars_files:
   - /home/ansible/key.yml
  tasks:
   - name: create 1 gb standard stoage and assing to specific instance.
     ec2_vol:
      aws_access_key: "{{ aws_key }}"
      aws_secret_key: "{{ aws_secret }}"
      region: "{{ aws_region }}"
      device_name: /dev/sdd
      instance: i-0bf3dd2dcf3519a4c
      volume_size: 1
     
