--- # create i am user and assing required privileges
- hosts: localhost
  connection: local
  remote_user: ansible
  gather_facts: no
  become: yes
  vars_files:
   - /home/ansible/key.yml
  tasks:
   - name: create iam user and assing required privileges
     iam_user:
      aws_access_key: "{{ aws_key }}"
      aws_secret_key: "{{ aws_secret }}"
      region: "{{ aws_region }}"
      name: srihari
      state: present
      managed_policy:
       - arn:aws:iam::aws:policy/AlexaForBusinessDeviceSetup
       - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
     register: results
   - name: display deatils
     debug: var=results
