- hosts: webserver
  sudo: yes
  connection: ssh
  gather_facts: no
  remote_user: ansible
  tasks:
   - name: install elinks
     action: copy src=/tmp/copy.txt dest=/tmp/copy.txt owner=root group=root
